name: Automacao Diaria Jarvis

on:
  schedule:
    # Roda a cada 1 hora automaticamente
    - cron: '0 * * * *'
  workflow_dispatch: # Permite que você rode manualmente se quiser

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissão para o Jarvis salvar os dados no seu GitHub

    steps:
      - name: 📥 Baixando Repositorio
        uses: actions/checkout@v3

      - name: 🐍 Configurando Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 📦 Instalando Dependencias
        run: pip install pandas requests

      - name: 🚀 Rodar Jarvis (sync_data.py)
        run: python sync_data.py

      - name: 💾 Salvando Dados Novos
        run: |
          git config --global user.name "Jarvis Bot"
          git config --global user.email "bot@jarvis.ia"
          git add data/database_diario.csv
          git commit -m "📊 Sincronia Temporal v63.0 - 5 Temporadas" || echo "Sem mudanças"
          git push
